// <auto-generated />
using System;
using LegoTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LegoTracker.Data.Migrations
{
    [DbContext(typeof(LegoTrackerDbContext))]
    partial class LegoTrackerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("LegoTracker.Data.Entities.LegoColor", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTrans")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RgbHex")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Colors");
                });

            modelBuilder.Entity("LegoTracker.Data.Entities.LegoPart", b =>
                {
                    b.Property<string>("PartNum")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PartCategoryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PartNum");

                    b.HasIndex("PartCategoryId");

                    b.ToTable("Parts");
                });

            modelBuilder.Entity("LegoTracker.Data.Entities.LegoSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BoxArtLocalPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("BoxArtSourceUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("BuildStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("EstimatedValue")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Msrp")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PieceCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SetNum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("StorageLocationId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ThemeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SetNum")
                        .IsUnique();

                    b.HasIndex("StorageLocationId");

                    b.HasIndex("ThemeId");

                    b.ToTable("Sets");
                });

            modelBuilder.Entity("LegoTracker.Data.Entities.Minifig", b =>
                {
                    b.Property<string>("FigNum")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("FigNum");

                    b.ToTable("Minifigs");
                });

            modelBuilder.Entity("LegoTracker.Data.Entities.MissingPart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ColorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("IssueType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LegoSetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("PartNum")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ResolvedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ColorId");

                    b.HasIndex("LegoSetId");

                    b.HasIndex("PartNum");

                    b.ToTable("MissingParts");
                });

            modelBuilder.Entity("LegoTracker.Data.Entities.PartCategory", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PartCategories");
                });

            modelBuilder.Entity("LegoTracker.Data.Entities.SetInstructionManual", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("DownloadStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DownloadedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .HasColumnType("TEXT");

                    b.Property<int>("LegoSetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LocalFilePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LegoSetId");

                    b.ToTable("InstructionManuals");
                });

            modelBuilder.Entity("LegoTracker.Data.Entities.SetInventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ColorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ElementId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSpare")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LegoSetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PartNum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ColorId");

                    b.HasIndex("PartNum");

                    b.HasIndex("LegoSetId", "PartNum", "ColorId", "IsSpare");

                    b.ToTable("SetInventories");
                });

            modelBuilder.Entity("LegoTracker.Data.Entities.SetMinifig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FigNum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LegoSetId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FigNum");

                    b.HasIndex("LegoSetId");

                    b.ToTable("SetMinifigs");
                });

            modelBuilder.Entity("LegoTracker.Data.Entities.StorageLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentLocationId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParentLocationId");

                    b.ToTable("StorageLocations");
                });

            modelBuilder.Entity("LegoTracker.Data.Entities.Theme", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentThemeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParentThemeId");

                    b.ToTable("Themes");
                });

            modelBuilder.Entity("LegoTracker.Data.Entities.LegoPart", b =>
                {
                    b.HasOne("LegoTracker.Data.Entities.PartCategory", "PartCategory")
                        .WithMany()
                        .HasForeignKey("PartCategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PartCategory");
                });

            modelBuilder.Entity("LegoTracker.Data.Entities.LegoSet", b =>
                {
                    b.HasOne("LegoTracker.Data.Entities.StorageLocation", "StorageLocation")
                        .WithMany("Sets")
                        .HasForeignKey("StorageLocationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LegoTracker.Data.Entities.Theme", "Theme")
                        .WithMany("Sets")
                        .HasForeignKey("ThemeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("StorageLocation");

                    b.Navigation("Theme");
                });

            modelBuilder.Entity("LegoTracker.Data.Entities.MissingPart", b =>
                {
                    b.HasOne("LegoTracker.Data.Entities.LegoColor", "Color")
                        .WithMany()
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LegoTracker.Data.Entities.LegoSet", "LegoSet")
                        .WithMany("MissingParts")
                        .HasForeignKey("LegoSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LegoTracker.Data.Entities.LegoPart", "Part")
                        .WithMany()
                        .HasForeignKey("PartNum")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Color");

                    b.Navigation("LegoSet");

                    b.Navigation("Part");
                });

            modelBuilder.Entity("LegoTracker.Data.Entities.SetInstructionManual", b =>
                {
                    b.HasOne("LegoTracker.Data.Entities.LegoSet", "LegoSet")
                        .WithMany("InstructionManuals")
                        .HasForeignKey("LegoSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LegoSet");
                });

            modelBuilder.Entity("LegoTracker.Data.Entities.SetInventory", b =>
                {
                    b.HasOne("LegoTracker.Data.Entities.LegoColor", "Color")
                        .WithMany()
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LegoTracker.Data.Entities.LegoSet", "LegoSet")
                        .WithMany("Inventory")
                        .HasForeignKey("LegoSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LegoTracker.Data.Entities.LegoPart", "Part")
                        .WithMany("SetInventories")
                        .HasForeignKey("PartNum")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Color");

                    b.Navigation("LegoSet");

                    b.Navigation("Part");
                });

            modelBuilder.Entity("LegoTracker.Data.Entities.SetMinifig", b =>
                {
                    b.HasOne("LegoTracker.Data.Entities.Minifig", "Minifig")
                        .WithMany("SetMinifigs")
                        .HasForeignKey("FigNum")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LegoTracker.Data.Entities.LegoSet", "LegoSet")
                        .WithMany("Minifigs")
                        .HasForeignKey("LegoSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LegoSet");

                    b.Navigation("Minifig");
                });

            modelBuilder.Entity("LegoTracker.Data.Entities.StorageLocation", b =>
                {
                    b.HasOne("LegoTracker.Data.Entities.StorageLocation", "ParentLocation")
                        .WithMany("ChildLocations")
                        .HasForeignKey("ParentLocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentLocation");
                });

            modelBuilder.Entity("LegoTracker.Data.Entities.Theme", b =>
                {
                    b.HasOne("LegoTracker.Data.Entities.Theme", "ParentTheme")
                        .WithMany("ChildThemes")
                        .HasForeignKey("ParentThemeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentTheme");
                });

            modelBuilder.Entity("LegoTracker.Data.Entities.LegoPart", b =>
                {
                    b.Navigation("SetInventories");
                });

            modelBuilder.Entity("LegoTracker.Data.Entities.LegoSet", b =>
                {
                    b.Navigation("InstructionManuals");

                    b.Navigation("Inventory");

                    b.Navigation("Minifigs");

                    b.Navigation("MissingParts");
                });

            modelBuilder.Entity("LegoTracker.Data.Entities.Minifig", b =>
                {
                    b.Navigation("SetMinifigs");
                });

            modelBuilder.Entity("LegoTracker.Data.Entities.StorageLocation", b =>
                {
                    b.Navigation("ChildLocations");

                    b.Navigation("Sets");
                });

            modelBuilder.Entity("LegoTracker.Data.Entities.Theme", b =>
                {
                    b.Navigation("ChildThemes");

                    b.Navigation("Sets");
                });
#pragma warning restore 612, 618
        }
    }
}
